### ISSUE TITLE
monitor_site_locations is not v3 compatible.

### ISSUE THREAD

**Issue by barronh** [noaa-oar-arl/MONET#15]
Some progress and a problem:

I updated the print statements and fixed some of the division assumptions in CMAQ (past.utils.old_div doesn't work), and fixed some typos (e.g., pd.DatFrame -> pd.DataFrame).  I say this to highlight that I didn't stop at the first error I found (see https://github.com/barronh/MONET/tree/v3-compat). I'll do a pull request when the remaining issues have been resolved.

The aqs object is still not working. It is having trouble reading `MONET/data/monitoring_site_locations.hdf`. I've boiled it down to the code below. 

This seems related to a known issue (https://github.com/pandas-dev/pandas/issues/17540). Can you remake `monitoring_site_locations.hdf` in a v3 compatible format? Or is there a way to have MONET automatically regenerate it?

Reproduce problem (proposed fix below):
```
>>> import pandas as pd
^[[As = pd.read_hdf('/home/bhenders/devel/MONET/data/monitoring_site_locations.hdf')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/work/ROMO/anaconda3/envs/dev/lib/python3.5/site-packages/pandas/io/pytables.py", line 360, in read_hdf
    return store.select(key, auto_close=auto_close, **kwargs)
  File "/work/ROMO/anaconda3/envs/dev/lib/python3.5/site-packages/pandas/io/pytables.py", line 724, in select
    return it.get_result()
  File "/work/ROMO/anaconda3/envs/dev/lib/python3.5/site-packages/pandas/io/pytables.py", line 1423, in get_result
    results = self.func(self.start, self.stop, where)
  File "/work/ROMO/anaconda3/envs/dev/lib/python3.5/site-packages/pandas/io/pytables.py", line 717, in func
    columns=columns, **kwargs)
  File "/work/ROMO/anaconda3/envs/dev/lib/python3.5/site-packages/pandas/io/pytables.py", line 2851, in read
    start=_start, stop=_stop)
  File "/work/ROMO/anaconda3/envs/dev/lib/python3.5/site-packages/pandas/io/pytables.py", line 2400, in read_array
    data = node[start:stop]
  File "/work/ROMO/anaconda3/envs/dev/lib/python3.5/site-packages/tables/vlarray.py", line 685, in __getitem__
    return self.read(start, stop, step)
  File "/work/ROMO/anaconda3/envs/dev/lib/python3.5/site-packages/tables/vlarray.py", line 825, in read
    outlistarr = [atom.fromarray(arr) for arr in listarr]
  File "/work/ROMO/anaconda3/envs/dev/lib/python3.5/site-packages/tables/vlarray.py", line 825, in <listcomp>
    outlistarr = [atom.fromarray(arr) for arr in listarr]
  File "/work/ROMO/anaconda3/envs/dev/lib/python3.5/site-packages/tables/atom.py", line 1228, in fromarray
    return six.moves.cPickle.loads(array.tostring())
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 2: ordinal not in range(128)

```

**Comment by bbakernoaa** [comment]
@barron

I’ll regenerate it this weekend if I can. In the monet.obs.epa_util there is a function call read_monitor_file. If you delete the file it should regenerate it or at least creat a data frame. I don’t think it will save into that location.

**Comment by barronh** [comment]
I think there was already an automatic bypass that was failing because my pandas was 0.19.1 and functionality from v0.19.2 was necessary. Might add a version requirement in setup.py.
